global:
  # How frequently to scrape targets by default.
  scrape_interval: 1m
  # How long until a scrape request times out.
  scrape_timeout: 10s
  # How frequently to evaluate rules.
  evaluation_interval: 1m
  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  #external_labels:
  #  <labelname>: <labelvalue> ...
  # File to which PromQL queries are logged.
  # Reloading the configuration will reopen the file.
  #query_log_file: <string>

scrape_configs :
  # The job name assigned to scraped metrics by default.
  - job_name: td01
    # How frequently to scrape targets from this job.
    #scrape_interval: global_config.scrape_interval
    # Per-scrape timeout when scraping this job.
    #scrape_timeout: global_config.scrape_timeout
    # The HTTP resource path on which to fetch metrics from targets.
    metrics_path: /metrics
    # Configures the protocol scheme used for requests.
    scheme: http
    # Optional HTTP URL parameters.
    #params:
    #  <string>: [<string>, ...]
    # List of labeled statically configured targets for this job.
    static_configs:
      - targets : ['localhost:9090']