version: "3.3"

services:
  reservation:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    networks:
      - db_resa_net

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one
    ports:
        - "16686:16686"
    environment:
        - JAEGER_AGENT_HOST=jaeger
    networks:
        - db_resa_net
    restart: on-failure

networks:
  db_resa_net:
    external: true