version: '3.3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - tp2-network

  elasticsearch_exporter:
    container_name: exporter
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    command:
      - '--es.uri=http://elastic:9200'
    restart: always
    depends_on:
      - elastic
    ports:
      - "9114:9114"
    networks:
      - tp2-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana_container
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
    networks:
      - tp2-network

  prometheus:
    image: prom/prometheus:v2.30.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - tp2-network

  filebeat:
    build : ./
    container_name: filebeat
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks: 
      - tp2-network

networks:
  tp2-network: null
