version: "3.7"

networks:
    resa-network:

services:
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
        ports:
        - "9200:9200"
        environment:
        - discovery.type=single-node
        networks:
        - resa-network
    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.15.2
        ports:
        - "5601:5601"
        environment:
        - ELASTICSEARCHURL=http://elasticsearch
        networks:
        - resa-network