version: "3.7"

networks:
    local-network:
        name: local
services:
    elastic-search : 
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
        ports:
        - "9200:9200"
        environment:
        - discovery.type=single-node
        networks:
        - resa-network
    prom:
        image: prom/prometheus:v2.30.2
        ports:
        - "9090:9090"
        volumes:
        - /home/lumapps/Documents/devops2/TD01/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
        - local-network

    grafana:
        image: grafana/grafana:8.2.0
        ports:
        - "3000:3000"
        volumes:
        - /home/lumapps/Documents/devops2/TD01/grafana/provisioning/:/etc/grafana/provisioning/
        environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_DATABASE_TYPE=postgres
        - GF_DATABASE_HOST=postgres
        - GF_DATABASE_USER=user
        - GF_DATABASE_PASSWORD=password
        networks:
        - local-network
        restart: on-failure

    postgres:
        image: postgres:13
        environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=user
        - POSTGRES_DB=grafana
        networks:
        - local-network
        restart: on-failure
        
    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.15.2
        ports:
        - "5601:5601"
        environment:
        - ELASTICSEARCHURL=http://elasticsearch
        networks:
        - resa-network